
[[input.files]]
path = "content/post/assume-positive-intent.md"
url = "https://2kabhishek.github.io/blog/assume-positive-intent/"
title = "Assume Positive Intent and Build Trust"

[[input.files]]
path = "content/post/pending-code-reviews.md"
url = "https://2kabhishek.github.io/blog/pending-code-reviews/"
title = "Pending Code Reviews Are Blockers for Your Team ğŸš§"

[[input.files]]
path = "content/post/keybindings.md"
url = "https://2kabhishek.github.io/blog/keybindings/"
title = "Keybindings FTW! âŒ¨ï¸ğŸ¥‚"

[[input.files]]
path = "content/post/do-not-parse-ls.md"
url = "https://2kabhishek.github.io/blog/do-not-parse-ls/"
title = "Do Not Parse ls! (Use this instead) âŒğŸ“‚"

[[input.files]]
path = "content/post/zsh.md"
url = "https://2kabhishek.github.io/blog/how-i-organize-my-zsh-config/"
title = "How I organize my zsh config ğŸšğŸ“‚"

[[input.files]]
path = "content/post/be-good-at-open-source.md"
url = "https://2kabhishek.github.io/blog/how-to-be-good-at-open-source/"
title = "How to be good at Open Source ğŸ§‘â€ğŸ’»ğŸŒ"

[[input.files]]
path = "content/post/nerdy.md"
url = "https://2kabhishek.github.io/blog/nerdy.nvim-find-nerd-glyphs-easily/"
title = "Nerdy.nvim - Find Nerd Glyphs Easily ğŸ¤“ğŸ”­"

[[input.files]]
path = "content/post/think-like-architect.md"
url = "https://2kabhishek.github.io/blog/how-to-think-like-an-architect-%EF%B8%8F/"
title = "How to Think Like an Architect ğŸ§ ğŸ›ï¸"

[[input.files]]
path = "content/post/prompt-engg.md"
url = "https://2kabhishek.github.io/blog/prompt-engineering-101/"
title = "Prompt Engineering 101 ğŸ¤–ğŸª„"

[[input.files]]
path = "content/post/win2k.md"
url = "https://2kabhishek.github.io/blog/win2k-ultimate-dev-setup-for-windows/"
title = "win2k - Ultimate Dev Setup for Windows ğŸªŸğŸª„"

[[input.files]]
path = "content/post/tmux-tilit.md"
url = "https://2kabhishek.github.io/blog/tmux-tilit-better-tiling-for-tmux/"
title = "tmux-tilit - better tiling for tmux ğŸªŸğŸª“"

[[input.files]]
path = "content/post/co-author.md"
url = "https://2kabhishek.github.io/blog/co-author.nvim-add-commit-authors-from-nvim/"
title = "Co-author.nvim - Add commit authors from nvim ğŸ’»ğŸª„"

[[input.files]]
path = "content/post/posh2k.md"
url = "https://2kabhishek.github.io/blog/posh2k-a-universal-prompt-for-power-users/"
title = "Posh2K - A universal prompt for power users ğŸ’ªğŸŒˆ"

[[input.files]]
path = "content/post/dsa-is-overrated.md"
url = "https://2kabhishek.github.io/blog/dsa-is-overrated/"
title = "Data Structure and Algorithms are Overrated! ğŸš«ğŸª´"

[[input.files]]
path = "content/post/links-showcase.md"
url = "https://2kabhishek.github.io/blog/links-present-your-links-in-style/"
title = "Links - Present Your Links In Style ğŸ”—ğŸ”®"

[[input.files]]
path = "content/post/tmux2k.md"
url = "https://2kabhishek.github.io/blog/tmux2k-power-pizzazz-for-tmux/"
title = "Tmux2K - Power &amp; Pizzazz for tmux ğŸ¥ŠğŸ’…"

[[input.files]]
path = "content/post/projects-showcase-github.md"
url = "https://2kabhishek.github.io/blog/projects-showcase-all-your-projects-%EF%B8%8F/"
title = "Projects - Showcase All Your Projects ğŸ›ï¸ğŸ‡"

[[input.files]]
path = "content/post/five-git-tricks.md"
url = "https://2kabhishek.github.io/blog/five-git-tricks/"
title = "Five Git Tricks To Make Dev Work Easier â›‘ï¸ğŸ¤¹ğŸ¼"

[[input.files]]
path = "content/post/learnings-from-hacktoberfest.md"
url = "https://2kabhishek.github.io/blog/what-i-learned-from-hacktoberfest/"
title = "What I Learned From Hacktoberfest ğŸ¥³ğŸ§‘â€ğŸ’»"

[[input.files]]
path = "content/post/intro-to-github-actions.md"
url = "https://2kabhishek.github.io/blog/my-intro-to-github-actions-%EF%B8%8F/"
title = "My Intro To Github Actions âš™ï¸ğŸ¤·"

[[input.files]]
path = "content/post/fix-mysql-daemon-startup.md"
url = "https://2kabhishek.github.io/blog/mysql-daemon-startup-fix-%EF%B8%8F%EF%B8%8F/"
title = "MySQL Daemon Startup Fix ğŸ› ï¸ğŸ•µï¸"

[[input.files]]
path = "content/post/manage-your-github-projects.md"
url = "https://2kabhishek.github.io/blog/manage-github-projects-easily/"
title = "Manage GitHub Projects Easily â™»ğŸ“‚"

[[input.files]]
path = "content/post/remove-screen-flickering-obs.md"
url = "https://2kabhishek.github.io/blog/remove-screen-flickering-obs/"
title = "Remove Screen Flickering OBS ğŸ’»ğŸ“¹"

[[input.files]]
path = "content/post/sync-forked-repository.md"
url = "https://2kabhishek.github.io/blog/sync-forked-repository-with-upstream-%EF%B8%8F/"
title = "Sync Forked Repository With Upstream ğŸ”âœ”ï¸"

[[input.files]]
path = "content/post/chrome-dark-mode.md"
url = "https://2kabhishek.github.io/blog/enable-dark-mode-across-chrome/"
title = "Enable Dark Mode Across Chrome ğŸŒšğŸ˜"

[[input.files]]
path = "content/post/add-numbers-without-arithmetic.md"
url = "https://2kabhishek.github.io/blog/add-numbers-without-arithmetic-operators-%EF%B8%8F/"
title = "Add Numbers Without Arithmetic Operators ğŸ™…â€â™‚ï¸â•"

[[input.files]]
path = "content/post/control-android-device-from-pc.md"
url = "https://2kabhishek.github.io/blog/control-your-android-device-from-pc/"
title = "Control your Android device from PC ğŸ“±ğŸ’»"

[[input.files]]
path = "content/post/microsoft-loves-linux.md"
url = "https://2kabhishek.github.io/blog/microsoft-actually-loves%EF%B8%8F-linux/"
title = "Microsoft Actually Lovesï¸ Linux? ğŸ§â¤"

[[input.files]]
path = "content/post/trim-unnecessary-files-from-git.md"
url = "https://2kabhishek.github.io/blog/trim-unnecessary-files-from-git-history-%EF%B8%8F%EF%B8%8F/"
title = "Trim Unnecessary Files From Git History âœ‚ï¸ğŸ—ƒï¸"

[[input.files]]
path = "content/post/navigating-javascript.md"
url = "https://2kabhishek.github.io/blog/navigating-javascript-%EF%B8%8F/"
title = "Navigating JavaScript  ğŸ¤·â€â™‚ï¸ğŸ§­"

[[input.files]]
path = "content/post/shell-keybindings.md"
url = "https://2kabhishek.github.io/blog/shell-keybindings/"
title = "Must Know Shell Keybindings ğŸ§ğŸš"

[[input.files]]
path = "content/post/two-factor-authentication.md"
url = "https://2kabhishek.github.io/blog/two-factor-authentication/"
title = "Two Factor Authentication ğŸ”ğŸ‘¤"

[[input.files]]
path = "content/post/tracking-code-time.md"
url = "https://2kabhishek.github.io/blog/tracking-code-time-%EF%B8%8F/"
title = "Tracking Code Time â²ï¸ğŸ’»"

[[input.files]]
path = "content/post/password-managers-101.md"
url = "https://2kabhishek.github.io/blog/password-managers-101/"
title = "Password Managers 101 ğŸ”‘ğŸŒ"

[[input.files]]
path = "content/post/hidden-world-of-podcasts.md"
url = "https://2kabhishek.github.io/blog/hidden-world-of-podcasts-%EF%B8%8F/"
title = "Hidden World Of Podcasts ğŸ™ï¸ğŸ§"
