
[[input.files]]
path = "content/post/useful-shell-functions.md"
url = "https://2kabhishek.github.io/blog/post/useful-shell-functions/"
title = "Useful Shell Functions for Developers"

[[input.files]]
path = "content/post/assume-positive-intent.md"
url = "https://2kabhishek.github.io/blog/post/assume-positive-intent/"
title = "Assume Positive Intent and Build Trust"

[[input.files]]
path = "content/post/pending-code-reviews.md"
url = "https://2kabhishek.github.io/blog/post/pending-code-reviews/"
title = "Pending Code Reviews Are Blockers for Your Team ğŸš§"

[[input.files]]
path = "content/post/keybindings.md"
url = "https://2kabhishek.github.io/blog/post/keybindings/"
title = "Keybindings FTW! âŒ¨ï¸ğŸ¥‚"

[[input.files]]
path = "content/post/do-not-parse-ls.md"
url = "https://2kabhishek.github.io/blog/post/do-not-parse-ls/"
title = "Do Not Parse ls! (Use this instead) âŒğŸ“‚"

[[input.files]]
path = "content/post/zsh.md"
url = "https://2kabhishek.github.io/blog/post/zsh/"
title = "How I organize my zsh config ğŸšğŸ“‚"

[[input.files]]
path = "content/post/be-good-at-open-source.md"
url = "https://2kabhishek.github.io/blog/post/be-good-at-open-source/"
title = "How to be good at Open Source ğŸ§‘â€ğŸ’»ğŸŒ"

[[input.files]]
path = "content/post/nerdy.md"
url = "https://2kabhishek.github.io/blog/post/nerdy/"
title = "Nerdy.nvim - Find Nerd Glyphs Easily ğŸ¤“ğŸ”­"

[[input.files]]
path = "content/post/think-like-architect.md"
url = "https://2kabhishek.github.io/blog/post/think-like-architect/"
title = "How to Think Like an Architect ğŸ§ ğŸ›ï¸"

[[input.files]]
path = "content/post/prompt-engg.md"
url = "https://2kabhishek.github.io/blog/post/prompt-engg/"
title = "Prompt Engineering 101 ğŸ¤–ğŸª„"

[[input.files]]
path = "content/post/win2k.md"
url = "https://2kabhishek.github.io/blog/post/win2k/"
title = "win2k - Ultimate Dev Setup for Windows ğŸªŸğŸª„"

[[input.files]]
path = "content/post/tmux-tilit.md"
url = "https://2kabhishek.github.io/blog/post/tmux-tilit/"
title = "tmux-tilit - better tiling for tmux ğŸªŸğŸª“"

[[input.files]]
path = "content/post/co-author.md"
url = "https://2kabhishek.github.io/blog/post/co-author/"
title = "Co-author.nvim - Add commit authors from nvim ğŸ’»ğŸª„"

[[input.files]]
path = "content/post/posh2k.md"
url = "https://2kabhishek.github.io/blog/post/posh2k/"
title = "Posh2K - A universal prompt for power users ğŸ’ªğŸŒˆ"

[[input.files]]
path = "content/post/dsa-is-overrated.md"
url = "https://2kabhishek.github.io/blog/post/dsa-is-overrated/"
title = "Data Structure and Algorithms are Overrated! ğŸš«ğŸª´"

[[input.files]]
path = "content/post/links-showcase.md"
url = "https://2kabhishek.github.io/blog/post/links-showcase/"
title = "Links - Present Your Links In Style ğŸ”—ğŸ”®"

[[input.files]]
path = "content/post/tmux2k.md"
url = "https://2kabhishek.github.io/blog/post/tmux2k/"
title = "Tmux2K - Power &amp; Pizzazz for tmux ğŸ¥ŠğŸ’…"

[[input.files]]
path = "content/post/projects-showcase-github.md"
url = "https://2kabhishek.github.io/blog/post/projects-showcase-github/"
title = "Projects - Showcase All Your Projects ğŸ›ï¸ğŸ‡"

[[input.files]]
path = "content/post/five-git-tricks.md"
url = "https://2kabhishek.github.io/blog/post/five-git-tricks/"
title = "Five Git Tricks To Make Dev Work Easier â›‘ï¸ğŸ¤¹ğŸ¼"

[[input.files]]
path = "content/post/learnings-from-hacktoberfest.md"
url = "https://2kabhishek.github.io/blog/post/learnings-from-hacktoberfest/"
title = "What I Learned From Hacktoberfest ğŸ¥³ğŸ§‘â€ğŸ’»"

[[input.files]]
path = "content/post/intro-to-github-actions.md"
url = "https://2kabhishek.github.io/blog/post/intro-to-github-actions/"
title = "My Intro To Github Actions âš™ï¸ğŸ¤·"

[[input.files]]
path = "content/post/fix-mysql-daemon-startup.md"
url = "https://2kabhishek.github.io/blog/post/fix-mysql-daemon-startup/"
title = "MySQL Daemon Startup Fix ğŸ› ï¸ğŸ•µï¸"

[[input.files]]
path = "content/post/manage-your-github-projects.md"
url = "https://2kabhishek.github.io/blog/post/manage-your-github-projects/"
title = "Manage GitHub Projects Easily â™»ğŸ“‚"

[[input.files]]
path = "content/post/remove-screen-flickering-obs.md"
url = "https://2kabhishek.github.io/blog/post/remove-screen-flickering-obs/"
title = "Remove Screen Flickering OBS ğŸ’»ğŸ“¹"

[[input.files]]
path = "content/post/sync-forked-repository.md"
url = "https://2kabhishek.github.io/blog/post/sync-forked-repository/"
title = "Sync Forked Repository With Upstream ğŸ”âœ”ï¸"

[[input.files]]
path = "content/post/chrome-dark-mode.md"
url = "https://2kabhishek.github.io/blog/post/chrome-dark-mode/"
title = "Enable Dark Mode Across Chrome ğŸŒšğŸ˜"

[[input.files]]
path = "content/post/add-numbers-without-arithmetic.md"
url = "https://2kabhishek.github.io/blog/post/add-numbers-without-arithmetic/"
title = "Add Numbers Without Arithmetic Operators ğŸ™…â€â™‚ï¸â•"

[[input.files]]
path = "content/post/control-android-device-from-pc.md"
url = "https://2kabhishek.github.io/blog/post/control-android-device-from-pc/"
title = "Control your Android device from PC ğŸ“±ğŸ’»"

[[input.files]]
path = "content/post/microsoft-loves-linux.md"
url = "https://2kabhishek.github.io/blog/post/microsoft-loves-linux/"
title = "Microsoft Actually Lovesï¸ Linux? ğŸ§â¤"

[[input.files]]
path = "content/post/trim-unnecessary-files-from-git.md"
url = "https://2kabhishek.github.io/blog/post/trim-unnecessary-files-from-git/"
title = "Trim Unnecessary Files From Git History âœ‚ï¸ğŸ—ƒï¸"

[[input.files]]
path = "content/post/navigating-javascript.md"
url = "https://2kabhishek.github.io/blog/post/navigating-javascript/"
title = "Navigating JavaScript  ğŸ¤·â€â™‚ï¸ğŸ§­"

[[input.files]]
path = "content/post/shell-keybindings.md"
url = "https://2kabhishek.github.io/blog/post/shell-keybindings/"
title = "Must Know Shell Keybindings ğŸ§ğŸš"

[[input.files]]
path = "content/post/two-factor-authentication.md"
url = "https://2kabhishek.github.io/blog/post/two-factor-authentication/"
title = "Two Factor Authentication ğŸ”ğŸ‘¤"

[[input.files]]
path = "content/post/tracking-code-time.md"
url = "https://2kabhishek.github.io/blog/post/tracking-code-time/"
title = "Tracking Code Time â²ï¸ğŸ’»"

[[input.files]]
path = "content/post/password-managers-101.md"
url = "https://2kabhishek.github.io/blog/post/password-managers-101/"
title = "Password Managers 101 ğŸ”‘ğŸŒ"

[[input.files]]
path = "content/post/hidden-world-of-podcasts.md"
url = "https://2kabhishek.github.io/blog/post/hidden-world-of-podcasts/"
title = "Hidden World Of Podcasts ğŸ™ï¸ğŸ§"
